// <auto-generated />
using System;
using AiAvatar.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiAvatar.Backend.Migrations
{
    [DbContext(typeof(AvatarDbContext))]
    partial class AvatarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AiAvatar.Backend.Data.Entities.ConversationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("AiAvatar.Backend.Data.Entities.LlmTelemetryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LoadDurationMs")
                        .HasColumnType("REAL");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TotalDurationMs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("LlmTelemetry", (string)null);
                });

            modelBuilder.Entity("AiAvatar.Backend.Data.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emotion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("EmotionIntensity")
                        .HasColumnType("REAL");

                    b.Property<string>("Gesture")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("GestureIntensity")
                        .HasColumnType("REAL");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TurnId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAtUtc");

                    b.HasIndex("TurnId", "Role")
                        .IsUnique()
                        .HasFilter("\"TurnId\" IS NOT NULL");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("AiAvatar.Backend.Data.Entities.TtsTelemetryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("AudioDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RealTimeFactor")
                        .HasColumnType("REAL");

                    b.Property<long>("SynthesisDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UsedCuda")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsedFp16")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoiceSource")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("TtsTelemetry", (string)null);
                });

            modelBuilder.Entity("AiAvatar.Backend.Data.Entities.LlmTelemetryEntity", b =>
                {
                    b.HasOne("AiAvatar.Backend.Data.Entities.MessageEntity", "Message")
                        .WithOne("LlmTelemetry")
                        .HasForeignKey("AiAvatar.Backend.Data.Entities.LlmTelemetryEntity", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("AiAvatar.Backend.Data.Entities.MessageEntity", b =>
                {
                    b.HasOne("AiAvatar.Backend.Data.Entities.ConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("AiAvatar.Backend.Data.Entities.TtsTelemetryEntity", b =>
                {
                    b.HasOne("AiAvatar.Backend.Data.Entities.MessageEntity", "Message")
                        .WithOne("TtsTelemetry")
                        .HasForeignKey("AiAvatar.Backend.Data.Entities.TtsTelemetryEntity", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("AiAvatar.Backend.Data.Entities.ConversationEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AiAvatar.Backend.Data.Entities.MessageEntity", b =>
                {
                    b.Navigation("LlmTelemetry");

                    b.Navigation("TtsTelemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
